user  angie;
#worker_processes  auto;
#worker_rlimit_nofile 65536;
worker_processes 1;  # otherwise: auto = logical CPU-cores
worker_rlimit_nofile 12000;  # 2 * worker_processes * worker_connections

error_log  /var/log/angie/error.log notice;
pid        /run/angie.pid;

# order
load_module modules/ngx_http_zstd_filter_module.so;
load_module modules/ngx_http_zstd_static_module.so;
load_module modules/ngx_http_brotli_filter_module.so;
load_module modules/ngx_http_brotli_static_module.so;

events {
  worker_connections 3000; # 65536;
  multi_accept on;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout  60;
  keepalive_requests 1000;
  types_hash_max_size 2048;
  server_tokens off;

  resolver 127.0.0.11 ipv6=off valid=30s;  # docker
  #resolver 1.1.1.1; # ipv6=off;

  send_timeout 3;
  reset_timedout_connection on;

  include http.d/_tls-common.config;

  include prometheus_all.conf;

  include       /etc/angie/mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  log_format extended '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" rt="$request_time" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      'h="$host" sn="$server_name" ru="$request_uri" u="$uri" '
                      'ucs="$upstream_cache_status" ua="$upstream_addr" us="$upstream_status" '
                      'uct="$upstream_connect_time" urt="$upstream_response_time"';

  access_log  /var/log/angie/access.log  main;

  include /etc/angie/http.d/*.conf;
}

stream {
    include /etc/angie/stream.d/*.conf;
}
