### HTTPS ###
###
server {
  listen 8080;
  listen 443 ssl;  # http2 - 1.9.5-1.25.0
  listen 443 quic;  # quic - 1.25.1+
#  listen [::]:443 ssl;  # http2 - 1.9.5-1.25.0
#  listen [::]:443 quic;
 add_header Alt-Svc 'h3=":443"; ma=86400';
  server_name  angie.localhost;

  access_log /var/log/angie/angie.localhost-https-access.log  combined  buffer=4k flush=5s;
  error_log  /var/log/angie/angie.localhost-https-error.log  error;

  root /usr/share/angie/html;
  index index.html index.htm index.php;

  include http.d/_tls-12.config;
#  include http.d/_tls-hsts.config;
#  include http.d/_tls-xss-block.config;

  include http.d/_tls-cert-snakeoil.config;
  ssl_stapling off;  # disabled special for snakeoil SSL-certificate

  location = /_livez {
    access_log off;
    default_type text/plain;
    return 200;
  }
  location /console/ {
    allow 127.0.0.1;
    allow 178.46.70.237; ## any host
    #deny all;

    alias /usr/share/angie-console-light/html/;
    index index.html;
    auth_basic "Log on";
    auth_basic_user_file http.d/demo_htpasswd;

    location /console/api/ {
        api /status/;
    }
  }

  location /metrics {
    prometheus all;
  }
}
