map $request_uri $block_req {
  default 0;
  "/updates.php" 1;
  "~*\/wordpress.*" 1;
  "~*\/admin.*" 1;
  "~*\/wp-.*" 1;
}

### HTTPS ###
###
server {
  listen 8080;
  listen 443 ssl;  # http2 - 1.9.5-1.25.0
  listen 443 quic;  # quic - 1.25.1+
#  listen [::]:443 ssl;  # http2 - 1.9.5-1.25.0
#  listen [::]:443 quic;
# add_header Alt-Svc 'h3=":443"; ma=86400';
  server_name  old-site.localhost;

  access_log off; # /var/log/angie/old-site-https-access.log  combined  buffer=4k flush=5s;
  error_log  /dev/null crit; #/var/log/angie/old-site-https-error.log  error;

  root /usr/share/angie/html;
  index index.html index.htm index.php;

  include http.d/_tls-12.config;
#  include http.d/_tls-hsts.config;
#  include http.d/_tls-xss-block.config;

  include http.d/_tls-cert-snakeoil.config;
  ssl_stapling off;  # disabled special for snakeoil SSL-certificate

# DENY access to .htaccess / .gitignore / .{any_file_starting_with_dot}
  location ~ /\. {
    deny  all;
    access_log off;
  }
# BLOCK WP-scanners
  if ( $block_req ) {
    #default_type text/plain;
    #add_header Content-Type "text/plain";
    return 404 'Go home, nigers';
  }

  location / {
    proxy_pass http://back-old-site; # TO back-end
    proxy_set_header  X-Real-IP       $remote_addr;
    proxy_set_header  X-Forwarded-for $proxy_add_x_forwarded_for;
    #proxy_set_header  Host            $http_host;
    proxy_set_header  Host            prokat-bgo.ru;
    port_in_redirect off;
    proxy_connect_timeout 3;
    proxy_set_header Connection ""; # for 'proxy_http_version'
    proxy_http_version 1.1;         # for HTTP keepalive (on "Load Balancer")

    proxy_set_header Accept-Encoding ""; # for SUB_FILTER
    sub_filter_once off;
    sub_filter_types text/css text/javascript text/xml;
    sub_filter 'http://old-site' 'https://old-site';
    proxy_hide_header X-Powered-By;
    #zstd off;  # temporary WORKAROUND for bug ZSTD + SUB-FILTER. See: _zstd.conf. Fixed in Angie 1.6.1
  }
}

upstream back-old-site {
  zone 113-leon 1m;
  server 192.168.100.113:8180;
}
