### HTTPS ###
###
server {
  listen 8080;
#  listen 443 ssl;  # http2 - 1.9.5-1.25.0
#  listen 443 quic;  # quic - 1.25.1+
#  listen [::]:443 ssl;  # http2 - 1.9.5-1.25.0
#  listen [::]:443 quic;
# add_header Alt-Svc 'h3=":443"; ma=86400';
  server_name  test-rr.localhost;

  access_log off; # /var/log/angie/old-site-https-access.log  combined  buffer=4k flush=5s;
  error_log  /dev/null crit; #/var/log/angie/old-site-https-error.log  error;

  root /usr/share/angie/html;
  index index.html index.htm index.php;

  include http.d/_tls-12.config;
#  include http.d/_tls-hsts.config;
#  include http.d/_tls-xss-block.config;

  include http.d/_tls-cert-snakeoil.config;
  ssl_stapling off;  # disabled special for snakeoil SSL-certificate

  location / {
     proxy_pass http://back-test-rr;
  }

}

upstream back-test-rr {
  zone back-test-rr 10m;
  server 127.0.0.1:8001 weight=1;
  server 127.0.0.1:8002 weight=1;
}
server {
  listen  8001;
  listen  8002;

  default_type text/plain;
  return 200 $server_port\n;
}
