version: '2.4'
services:
# user UID & GID  MUST BE  equal local user ID
# rasla@devops-rasla:~/git/autoclassics/web$ id
# uid=1000(rasla) gid=1000(rasla) ...
  nginx:
    #container_name: php_nginx
# CPU Affinity, ex.: "0" / "2,3"
    cpuset: "0"
#    sysctls:
#      net.ipv4.ip_unprivileged_port_start: 80
    #hostname: nginx
    tmpfs:
      - /run:uid=${USER_UID}
      - /var/cache/nginx:uid=${USER_UID}
    user: ${USER_UID}:${USER_GID}

  php:
    build:
      #dockerfile: Dockerfile.php72
      args:
        UID: ${USER_UID}
        GID: ${USER_GID}
        # php
        MAX_EXECUTION_TIME: 30
        MEMORY_LIMIT: 256M
        UPLOAD_MAX_SIZE: 8M
        TIME_ZONE: Asia/Yekaterinburg  # Europe/Moscow
        # pecl
        #INSTALL_BCMATH: 1
        #INSTALL_GD: 1
        #INSTALL_MEMCACHED: 0
        #INSTALL_MYSQL: 1
        #INSTALL_PGSQL: 1
        #INSTALL_REDIS: 1
#    environment:
#  XDebug2 (PHP 5.6, 7.x) configure:  https://xdebug.org/docs/remote
#      XDEBUG_CONFIG: remote_enable=1 remote_host=192.168.1.241
#      PHP_IDE_CONFIG: serverName=proj-php
#  XDebug3 (PHP 8.0+): https://xdebug.org/docs/upgrade_guide
    user: ${USER_UID}:${USER_GID}

# docker network create app
#networks:
#  default:
#    external:
#      name: "app"
