version: '2.4'
services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - ${APP_HOST_PORT:-8080}:8080
    depends_on:
      - php
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php/app:/app:ro

  php:
    build:
      context: ./php/build
      dockerfile: Dockerfile.${APP_DOCKERFILE:-php74}
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./php/app:/app


# docker network create app
networks:
  default:
    external:
      name: "app"
