{
 "title": "VM - summary",
 "tags": [
  "node",
  "linux",
  "ssl"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Up",
   "type": "state-timeline",
   "description": "Is node UP ?",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "mysql-{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "FS available, ROOT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM Free & FS-Boot Free",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FS available, BOOT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{mountpoint=\"/boot\"}",
       "legendFormat": "{{instance}} - {{mountpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTPS Probes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "HTTPS Probe",
   "type": "state-timeline",
   "description": "Are websites available?",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SSL Expiry, days",
   "type": "status-history",
   "description": "How many days left until SSL-certificates will expire ?",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ceil((probe_ssl_earliest_cert_expiry - time() )/ 86400)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}